# Generated by Django 3.2.6 on 2021-08-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unite_organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_uo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=35)),
                ('prenom', models.CharField(max_length=25)),
                ('unite_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spas.unite_organisation')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='employe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='spas.employe'),
        ),
    ]
