# Generated by Django 3.2.6 on 2021-08-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0002_auto_20210811_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='employe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myuser', to='spas.employe'),
        ),
    ]
