# Generated by Django 3.2.6 on 2021-08-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0004_alter_myuser_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='employe',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to='spas.employe'),
            preserve_default=False,
        ),
    ]
