# Generated by Django 3.2.6 on 2021-08-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0005_alter_myuser_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='pseudo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Pseudo utilisateur'),
        ),
    ]
