# Generated by Django 3.2.6 on 2021-08-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0007_auto_20210813_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='materiel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='spas.materiel'),
            preserve_default=False,
        ),
    ]
