# Generated by Django 3.2.6 on 2021-08-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0008_affectation_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='type_m',
            field=models.CharField(choices=[('PREVENTIVE', 'PREVENTIVE'), ('CORRECTIVE', 'CORRECTIVE')], default='PREVENTIVE', max_length=11),
        ),
    ]
