# Generated by Django 3.2.6 on 2021-08-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0009_alter_maintenance_type_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date_d',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_f',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='etat_m',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='mt_m',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='obs_m',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
