# Generated by Django 3.2.6 on 2021-08-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0010_auto_20210816_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='commande',
            name='ref_c',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_c', models.CharField(max_length=50, unique=True)),
                ('date_c', models.DateField()),
                ('qte_c', models.IntegerField()),
                ('obs_c', models.CharField(max_length=50)),
                ('commande', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='spas.commande')),
                ('fourniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spas.fourniture')),
            ],
        ),
    ]
