# Generated by Django 3.2.6 on 2021-08-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0012_auto_20210825_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='fourniture',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='obs_s',
        ),
        migrations.AddField(
            model_name='sortie',
            name='ref_s',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='panier',
        ),
    ]
