# Generated by Django 3.2.6 on 2021-09-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0013_auto_20210826_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne_commande',
            name='prix_c',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
