# Generated by Django 3.2.6 on 2021-09-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0015_mouvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='ligne_appro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spas.ligne_entree'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='ligne_sortie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spas.ligne_sortie'),
        ),
    ]
