# Generated by Django 3.2.6 on 2021-10-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0017_seuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='consommable',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='employe',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='employe_service',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='fourniture',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='ligne_commande',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='ligne_commande',
            name='statut',
            field=models.CharField(choices=[('EN COURS', 'EN COURS'), ('LIVREE', 'LIVREE')], default='EN COURS', max_length=15),
        ),
        migrations.AddField(
            model_name='ligne_entree',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='ligne_entree',
            name='statut',
            field=models.CharField(choices=[('EN COURS', 'EN COURS'), ('EPUISEE', 'EPUISEE')], default='EN COURS', max_length=15),
        ),
        migrations.AddField(
            model_name='ligne_sortie',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='materiel',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='modele_mat',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='type',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='unite_organisation',
            name='etat',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=15),
        ),
    ]
