# Generated by Django 3.2.6 on 2021-10-04 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0019_alter_ligne_entree_fourniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvement',
            name='fourniture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spas.ligne_commande'),
        ),
    ]
