# Generated by Django 3.2.6 on 2021-10-05 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0020_alter_mouvement_fourniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligne_sortie',
            name='fourniture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spas.ligne_commande'),
        ),
    ]
