# Generated by Django 3.2.6 on 2021-10-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0021_alter_ligne_sortie_fourniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligne_entree',
            name='fourniture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spas.fourniture'),
        ),
        migrations.AlterField(
            model_name='ligne_sortie',
            name='fourniture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spas.fourniture'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='fourniture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spas.fourniture'),
        ),
    ]
