# Generated by Django 3.2.6 on 2021-10-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0022_auto_20211005_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligne_commande',
            name='fourniture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spas.fourniture'),
        ),
    ]
