# Generated by Django 3.2.6 on 2021-10-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0023_auto_20211007_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourniture',
            name='qte_seuil',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
