# Generated by Django 3.2.6 on 2021-10-12 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0024_fourniture_qte_seuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne_commande',
            name='consommable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spas.consommable'),
        ),
    ]
