# Generated by Django 3.2.6 on 2022-01-05 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0025_ligne_commande_consommable'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourniture',
            name='base',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fourniture',
            name='mesure',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligne_entree',
            name='commande',
            field=models.ForeignKey(default=41, on_delete=django.db.models.deletion.CASCADE, to='spas.ligne_commande'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligne_sortie',
            name='lentree',
            field=models.ForeignKey(default=220, on_delete=django.db.models.deletion.CASCADE, to='spas.ligne_entree'),
            preserve_default=False,
        ),
    ]
