# Generated by Django 3.2.6 on 2022-01-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0028_remove_sortie_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligne_entree',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spas.ligne_commande'),
        ),
    ]
