# Generated by Django 4.1.1 on 2022-09-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0031_auto_20220106_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='employe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spas.employe'),
        ),
    ]
